### ISSUE TITLE
SN30 Pro firmware 1.38 ?

### ISSUE THREAD

**Issue by escape75** [fwupd/8bitdo-firmware#40]
Where can we find firmware 1.38 for the SN30 Pro, I see 1.37 is the latest ?

**Comment by hughsie** [comment]
8bitdo isn't uploading firmware anymore I'm afraid.

**Comment by escape75** [comment]
Ok, sounds good, I actually now have SN30Pro_1.38.dat and SN30ProPlus_5.04.dat but I'm not sure if I can share.

**Comment by hughsie** [comment]
I don't mind links here, but you obviously can't post them as files on github. I'll close this issue now. If you can both email 8bitdo and ask them to continue uploading firmware that would be helpful.
